#!/bin/bash
#
### BEGIN INIT INFO
# Provides: $storm-pacemaker
# Default-Start: 3 4 5
# Default-Stop: 0 1 6
### END INIT INFO

# Source function library.
. /etc/init.d/functions
RETVAL=0

STORM_USER=storm
install -d -m 0755 -o storm -g storm /var/run/storm
PID_FILE="/var/run/storm/storm-pacemaker.pid"

start() {
    if storm_status>/dev/null; then
	    echo "Storm pacemaker is already running."
	    exit 1
    else
	    echo "Starting storm pacemaker..."
    fi 
    STORM_CMD="/opt/storm/bin/storm pacemaker &"
    runuser --shell=/bin/bash --preserve-environment $STORM_USER --command="$STORM_CMD > /dev/null && echo \$! > $PID_FILE"
    RETVAL=$?
    storm_status
    return $RETVAL
}

stop() {
    if storm_status; then
        echo "Stopping storm pacemaker..."
        killproc -p $PID_FILE -TERM
        RETVAL=$?
        storm_status
    else
        return 0
    fi
    return $RETVAL
}

storm_status() {
    status -p $PID_FILE storm-pacemaker
    return $?
}

restart() {
        stop
        start
}

reload()  {
    restart
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  status)
        storm_status
        ;;
  restart)
        restart
        ;;
  reload)
        reload
        ;;
  *)
        echo $"Usage: $0 {start|stop|status|restart}"
        exit 2
esac

exit $?

